baseURL = "https://alemorm.github.io/foveated-imaging/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "docs"
DefaultContentLanguage = "en"
languageCode = "en-us"
title = "Foveated Imaging"
theme = "hugo-theme-blueberry-detox"
enableInlineShortcodes = true
enableGitInfo = true
canonifyurls = true

[Params]
    description = "An interactive web application"
    showTime = false
    dateFormat = "2006"
    commit = "https://github.com/alemorm/foveated-imaging/tree/"

[Author]
  name = "Alejandro Morales & Liang Shi"
  email = "alegmoralesm@gmail.com"
  gitlab = "amoralesmartinez"
  github = "alemorm"
  linkedin = "alegmoralesm"